#!/usr/bin/env python3
"""Post-process a font_to_py module so the digits 0-9 are *tabular* (uniform width).

font_to_py proportional fonts give "1" a narrower advance than the other numerals, so a
departure board's times don't line up. This pads every digit narrower than the widest digit
with blank columns ON THE RIGHT, bringing them all to the same width (the requested fix).
No-op on monospaced fonts (digits are already uniform).

Usage:  python tabular_digits.py path/to/dotmatrixNN.py   # rewrites the file in place
"""

import importlib.util
import sys

DIGITS = "0123456789"


def _load(path):
    spec = importlib.util.spec_from_file_location("dmfont", path)
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    return m


def _emit_bytes(name, data):
    out = name + " =\\\n"
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        out += "b'" + "".join("\\x%02x" % b for b in chunk) + "'"
        out += "\\\n" if i + 16 < len(data) else "\n"
    return out


def _decode(bmp, H, w):
    bpr = (w - 1) // 8 + 1
    return [[(bmp[r * bpr + c // 8] >> (7 - (c % 8))) & 1 for c in range(w)] for r in range(H)]


def _encode(bits, H, w):
    bpr = (w - 1) // 8 + 1
    out = bytearray(bpr * H)
    for r in range(H):
        for c in range(w):
            if bits[r][c]:
                out[r * bpr + c // 8] |= 0x80 >> (c % 8)
    return bytes(out)


def _center(bmp, H, old_w, new_w):
    """Re-pack an hmap glyph into new_w columns with its ink horizontally centered.

    Centring (rather than dumping all the slack on the right) makes a narrow digit like "1"
    sit balanced in its tabular cell, matching the visual rhythm of the wider numerals.
    """
    bits = _decode(bmp, H, old_w)
    cols = [c for r in range(H) for c in range(old_w) if bits[r][c]]
    new_bits = [[0] * new_w for _ in range(H)]
    if cols:
        lo, hi = min(cols), max(cols)
        off = (new_w - (hi - lo + 1)) // 2 - lo
        for r in range(H):
            for c in range(old_w):
                if bits[r][c]:
                    nc = c + off
                    if 0 <= nc < new_w:
                        new_bits[r][nc] = 1
    return _encode(new_bits, H, new_w)


def process(path):
    m = _load(path)
    H = m.height()
    font, index = m._font, m._index
    nslots = len(index) // 2 - 1  # final index entry is a length sentinel
    offs = [index[2 * i] | (index[2 * i + 1] << 8) for i in range(len(index) // 2)]

    glyphs = []  # [width, bitmap] per slot
    for i in range(nslots):
        d = offs[i]
        w = font[d] | (font[d + 1] << 8)
        bpr = (w - 1) // 8 + 1
        glyphs.append([w, bytes(font[d + 2:d + 2 + bpr * H])])

    digit_slots = [ord(c) - 32 + 1 for c in DIGITS]  # char c -> slot (c-32+1)
    max_dw = max(glyphs[s][0] for s in digit_slots)
    changed = 0
    # Centre every digit's ink in a uniform max-width cell. For proportional fonts this
    # widens narrow digits (e.g. "1"); for monospaced fonts the width is already uniform but
    # this re-centres the ink so a left-hugging "1" sits balanced like the others.
    for s in digit_slots:
        w, bmp = glyphs[s]
        new_bmp = _center(bmp, H, w, max_dw)
        if w != max_dw or new_bmp != bmp:
            glyphs[s] = [max_dw, new_bmp]
            changed += 1

    # Rebuild _font + _index (+ sentinel).
    new_font = bytearray()
    new_offs = []
    for w, bmp in glyphs:
        new_offs.append(len(new_font))
        new_font += bytes([w & 0xFF, (w >> 8) & 0xFF]) + bmp
    new_offs.append(len(new_font))
    new_index = bytearray()
    for o in new_offs:
        new_index += bytes([o & 0xFF, (o >> 8) & 0xFF])

    max_width = max(g[0] for g in glyphs)
    min_ch = m.min_ch() if hasattr(m, "min_ch") else 32
    max_ch = m.max_ch() if hasattr(m, "max_ch") else 126
    baseline = m.baseline() if hasattr(m, "baseline") else H

    src = []
    src.append("# Code generated by font_to_py.py, digits made tabular by tabular_digits.py.")
    src.append("# Font: dot-matrix-regular.ttf")
    src.append("version = '0.42'")
    src.append("")
    for fn, val in (("height", H), ("baseline", baseline), ("max_width", max_width)):
        src.append("def %s():\n    return %d\n" % (fn, val))
    for fn, val in (("hmap", m.hmap()), ("reverse", m.reverse()), ("monospaced", m.monospaced())):
        src.append("def %s():\n    return %s\n" % (fn, val))
    for fn, val in (("min_ch", min_ch), ("max_ch", max_ch)):
        src.append("def %s():\n    return %d\n" % (fn, val))
    src.append(_emit_bytes("_font", bytes(new_font)))
    src.append(_emit_bytes("_index", bytes(new_index)))
    src.append("_mvfont = memoryview(_font)")
    src.append("_mvi = memoryview(_index)")
    src.append("ifb = lambda l : l[0] | (l[1] << 8)")
    src.append("")
    src.append("def get_ch(ch):")
    src.append("    oc = ord(ch)")
    src.append("    ioff = 2 * (oc - %d + 1) if oc >= %d and oc <= %d else 0" % (min_ch, min_ch, max_ch))
    src.append("    doff = ifb(_mvi[ioff : ])")
    src.append("    width = ifb(_mvfont[doff : ])")
    src.append("")
    src.append("    next_offs = doff + 2 + ((width - 1)//8 + 1) * %d" % H)
    src.append("    return _mvfont[doff + 2:next_offs], %d, width" % H)
    src.append("")

    with open(path, "w") as f:
        f.write("\n".join(src))
    return changed, max_dw


if __name__ == "__main__":
    for p in sys.argv[1:]:
        n, w = process(p)
        print("%s: padded %d digit(s) to width %d" % (p, n, w))
